# =========================================
# TIDB CLOUD DATABASE
# =========================================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================
# JPA
# =========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================
# OPENWEATHER
# =========================================

openweather.api.key=${OPENWEATHER_API_KEY}

# =========================================
# MSG91
# =========================================

msg91.auth-key=${MSG91_AUTH_KEY}
msg91.flow-id=${MSG91_FLOW_ID}
msg91.sender-id=${MSG91_SENDER_ID}
admin.mobile=${ADMIN_MOBILE}

# =========================================
# GOOGLE OAUTH2
# =========================================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# =========================================
# GITHUB OAUTH2
# =========================================

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# =========================================
# LOGGING
# =========================================

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

# =========================================
# SENDLIB EMAIL API
# =========================================

sendlib.api-key=${SENDLIB_API_KEY}
sendlib.sender-email=${SENDLIB_SENDER_EMAIL}
# =========================================================
# TEXTBELT SMS - SOS
# =========================================================

textbelt.api.url=https://textbelt.com/text
textbelt.api.key=textbelt
textbelt.emergency.phone=+918247469010
